import React, { useState, useEffect } from 'react';
import { PatientRecord, TriageAgentResult, VitalSigns, LabBiomarkers } from '../types/clinical';
import { BENCHMARK_PATIENTS } from '../data/syntheticPatients';
import { 
  HeartPulse, 
  AlertTriangle, 
  ShieldCheck, 
  CheckCircle2, 
  Clock, 
  Stethoscope, 
  FileText, 
  ArrowRight, 
  Activity, 
  Layers, 
  Copy, 
  Check, 
  RefreshCw, 
  PlusCircle, 
  Zap,
  Info,
  ChevronDown,
  ChevronUp,
  AlertCircle
} from 'lucide-react';

interface TriageWorkspaceProps {
  onPatientSelect?: (patient: PatientRecord) => void;
}

export const TriageWorkspace: React.FC<TriageWorkspaceProps> = () => {
  const [selectedPatient, setSelectedPatient] = useState<PatientRecord>(BENCHMARK_PATIENTS[0]);
  const [isRunningAgent, setIsRunningAgent] = useState<boolean>(false);
  const [agentResult, setAgentResult] = useState<TriageAgentResult | null>(null);
  const [activeStepIndex, setActiveStepIndex] = useState<number>(0);
  const [copiedSOAP, setCopiedSOAP] = useState<boolean>(false);
  const [showCustomModal, setShowCustomModal] = useState<boolean>(false);
  const [expandedTraceIndex, setExpandedTraceIndex] = useState<number | null>(null);

  // Custom Patient form state (Indian name default)
  const [customForm, setCustomForm] = useState<Partial<PatientRecord>>({
    name: 'Pooja Sharma',
    age: 45,
    gender: 'FEMALE',
    chiefComplaint: 'Sudden chest pain, mild dizziness, and fast heartbeat for 2 hours',
    symptomDurationHours: 2,
    pastMedicalHistory: ['High Blood Pressure'],
    currentMedications: ['Amlodipine 5mg (daily)'],
    proposedMedications: ['Aspirin 325mg Oral', 'Nitroglycerin 0.4mg Under Tongue'],
    allergies: ['No Known Allergies'],
    vitals: {
      heartRate: 98,
      systolicBP: 138,
      diastolicBP: 88,
      respiratoryRate: 20,
      oxygenSaturation: 96,
      temperature: 37.0,
      gcsScore: 15,
      painScore: 7
    },
    labs: {
      troponinI: 0.12,
      lactate: 1.2,
      whiteBloodCellCount: 8.5,
      bloodGlucose: 110,
      serumCreatinine: 0.9
    }
  });

  // Automatically execute agent when patient changes
  useEffect(() => {
    handleRunAgent(selectedPatient);
  }, [selectedPatient]);

  const handleRunAgent = async (patient: PatientRecord) => {
    setIsRunningAgent(true);
    setActiveStepIndex(0);

    // Simulate animated step progression for UI responsiveness
    const stepInterval = setInterval(() => {
      setActiveStepIndex(prev => (prev < 4 ? prev + 1 : prev));
    }, 180);

    try {
      const response = await fetch('/api/agent/triage', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(patient)
      });

      if (!response.ok) {
        throw new Error(`Server returned status ${response.status}`);
      }

      const data: TriageAgentResult = await response.json();
      clearInterval(stepInterval);
      setActiveStepIndex(4);
      setAgentResult(data);
    } catch (err) {
      console.warn('Network agent triage fetch failed, invoking direct client fallback engine:', err);
      // Resilient client-side fallback
      try {
        const { runClinicalAgent } = await import('../agent/clinicalAgent');
        const fallbackResult = await runClinicalAgent(patient);
        clearInterval(stepInterval);
        setActiveStepIndex(4);
        setAgentResult(fallbackResult);
      } catch (clientErr) {
        console.error('Complete triage failure:', clientErr);
      }
    } finally {
      setIsRunningAgent(false);
    }
  };

  const handleCopySOAP = () => {
    if (!agentResult?.clinicalSynthesis?.soapNote) return;
    const s = agentResult.clinicalSynthesis.soapNote;
    const text = `DOCTOR'S CLINICAL NOTE - MEDGUARD AI\nPatient: ${selectedPatient.name} (${selectedPatient.age} years old, ${selectedPatient.gender})\nDate: ${new Date().toLocaleString()}\n\n[SUBJECTIVE - Patient Symptoms]\n${s.subjective}\n\n[OBJECTIVE - Vitals & Test Results]\n${s.objective}\n\n[ASSESSMENT - Diagnosis & Risk Level]\n${s.assessment}\n\n[PLAN - Treatment & Medicines]\n${s.plan}\n\nRecommended Ward: ${agentResult.clinicalSynthesis.dispositionRecommendation}\nGenerated by: MedGuard AI Hospital System`;
    navigator.clipboard.writeText(text);
    setCopiedSOAP(true);
    setTimeout(() => setCopiedSOAP(false), 2500);
  };

  const getTriageColor = (category?: string) => {
    switch (category) {
      case 'RESUSCITATION':
        return {
          bg: 'bg-rose-50 border-rose-200 text-rose-950 shadow-rose-100',
          badge: 'bg-rose-600 text-white',
          label: 'Level 1 - Immediate Emergency (Life-Threatening / Needs Instant Care)',
          dot: 'bg-rose-500',
          tag: 'text-rose-700 bg-rose-100/80'
        };
      case 'EMERGENT':
        return {
          bg: 'bg-amber-50 border-amber-200 text-amber-950 shadow-amber-100',
          badge: 'bg-amber-600 text-white',
          label: 'Level 2 - High Emergency (High Risk / Needs Doctor within 10 mins)',
          dot: 'bg-amber-500',
          tag: 'text-amber-800 bg-amber-100/80'
        };
      case 'URGENT':
        return {
          bg: 'bg-sky-50 border-sky-200 text-sky-950 shadow-sky-100',
          badge: 'bg-sky-600 text-white',
          label: 'Level 3 - Urgent (Needs Hospital Tests & Treatment)',
          dot: 'bg-sky-500',
          tag: 'text-sky-800 bg-sky-100/80'
        };
      case 'LESS_URGENT':
        return {
          bg: 'bg-teal-50 border-teal-200 text-teal-950 shadow-teal-100',
          badge: 'bg-teal-600 text-white',
          label: 'Level 4 - Less Urgent (Needs 1 Simple Test or Treatment)',
          dot: 'bg-teal-500',
          tag: 'text-teal-800 bg-teal-100/80'
        };
      default:
        return {
          bg: 'bg-emerald-50 border-emerald-200 text-emerald-950 shadow-emerald-100',
          badge: 'bg-emerald-600 text-white',
          label: 'Level 5 - Non-Urgent (Standard Clinic Consultation)',
          dot: 'bg-emerald-500',
          tag: 'text-emerald-800 bg-emerald-100/80'
        };
    }
  };

  const currentTriage = getTriageColor(agentResult?.mlAssessment?.triageCategory);

  const stepLabels = [
    '1. Calculate Risk',
    '2. Check Lab Tests',
    '3. Medical Guidelines',
    '4. Check Medicine Safety',
    '5. Create Care Plan'
  ];

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-6">
      {/* Benchmark Patient Case Selector */}
      <div className="bg-white border border-slate-200/80 rounded-2xl sm:rounded-3xl p-5 shadow-sm space-y-3">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div>
            <div className="flex items-center gap-2">
              <Stethoscope className="w-5 h-5 text-sky-600" />
              <h2 className="text-sm font-bold text-slate-900 uppercase tracking-wider">
                Select an Emergency Patient (Indian Cases)
              </h2>
            </div>
            <p className="text-xs text-slate-500 mt-0.5">
              Click any patient below to check their condition, vital signs, risk level, and medical treatment plan.
            </p>
          </div>
          <button
            id="create-custom-patient-btn"
            onClick={() => setShowCustomModal(true)}
            className="flex items-center gap-1.5 text-xs font-bold px-4 py-2 rounded-xl bg-sky-500 hover:bg-sky-600 text-white transition-all shadow-sm shadow-sky-500/20 self-start sm:self-auto cursor-pointer"
          >
            <PlusCircle className="w-4 h-4" />
            <span>+ Add New Patient</span>
          </button>
        </div>

        {/* Patient Selection Pills */}
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2.5 pt-1">
          {BENCHMARK_PATIENTS.map(patient => {
            const isSelected = selectedPatient.id === patient.id;
            return (
              <button
                key={patient.id}
                id={`patient-btn-${patient.id.toLowerCase()}`}
                onClick={() => setSelectedPatient(patient)}
                className={`p-3.5 rounded-2xl text-left transition-all border cursor-pointer ${
                  isSelected
                    ? 'bg-sky-500 text-white border-sky-600 shadow-md shadow-sky-500/25 ring-2 ring-sky-300'
                    : 'bg-slate-50 border-slate-200 hover:border-sky-300 hover:bg-white text-slate-700 hover:shadow-xs'
                }`}
              >
                <div className="flex items-center justify-between mb-1">
                  <span className={`text-xs font-bold ${isSelected ? 'text-white' : 'text-slate-900'}`}>
                    {patient.name}
                  </span>
                  <span className={`text-[10px] font-mono font-semibold ${isSelected ? 'text-sky-100' : 'text-slate-500'}`}>
                    {patient.age}y
                  </span>
                </div>
                <p className={`text-[11px] truncate font-medium ${isSelected ? 'text-sky-100' : 'text-slate-500'}`}>
                  {patient.chiefComplaint}
                </p>
              </button>
            );
          })}
        </div>
      </div>

      {/* Main Grid: Left = Patient Details & Vitals; Right = Agent Workspace & Clinical Decision */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Patient Intake & Telemetry Card */}
        <div className="lg:col-span-4 space-y-4">
          <div className="bg-white border border-slate-200/80 rounded-2xl sm:rounded-3xl p-6 shadow-sm space-y-5">
            {/* Header with Name & Demographics */}
            <div className="flex items-center justify-between pb-3 border-b border-slate-100">
              <div>
                <h3 className="font-bold text-lg text-slate-900">{selectedPatient.name}</h3>
                <p className="text-xs text-slate-500 font-mono">
                  ID: #{selectedPatient.id} • {selectedPatient.age} years old • {selectedPatient.gender}
                </p>
              </div>
              <button
                id="rerun-agent-btn"
                onClick={() => handleRunAgent(selectedPatient)}
                disabled={isRunningAgent}
                className="p-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-sky-600 transition-colors disabled:opacity-50 cursor-pointer"
                title="Re-run AI Analysis"
              >
                <RefreshCw className={`w-4 h-4 ${isRunningAgent ? 'animate-spin' : ''}`} />
              </button>
            </div>

            {/* Chief Complaint */}
            <div>
              <label className="text-[11px] uppercase tracking-wider text-slate-400 font-semibold block mb-1.5">
                Main Symptoms & Complaint
              </label>
              <div className="p-3.5 rounded-2xl bg-slate-50 border border-slate-200/70 text-xs text-slate-700 leading-relaxed">
                "{selectedPatient.chiefComplaint}"
                <div className="mt-2 flex items-center gap-1.5 text-[11px] text-sky-600 font-medium">
                  <Clock className="w-3 h-3" />
                  <span>Started: ~{selectedPatient.symptomDurationHours} hours ago</span>
                </div>
              </div>
            </div>

            {/* Vital Signs Grid */}
            <div>
              <label className="text-[11px] uppercase tracking-wider text-slate-400 font-semibold block mb-2">
                Patient Vital Signs (Live Telemetry)
              </label>
              <div className="grid grid-cols-2 gap-2.5">
                <div className="p-3 rounded-2xl bg-slate-50 border border-slate-200/70">
                  <div className="text-[10px] text-slate-400 font-semibold uppercase tracking-wider">Heart Rate</div>
                  <div className="flex items-baseline gap-1 mt-0.5">
                    <span className={`text-xl font-bold font-mono ${selectedPatient.vitals.heartRate > 100 || selectedPatient.vitals.heartRate < 50 ? 'text-rose-600' : 'text-slate-900'}`}>
                      {selectedPatient.vitals.heartRate}
                    </span>
                    <span className="text-[10px] text-slate-400 font-medium">BPM</span>
                  </div>
                </div>

                <div className="p-3 rounded-2xl bg-slate-50 border border-slate-200/70">
                  <div className="text-[10px] text-slate-400 font-semibold uppercase tracking-wider">Blood Pressure</div>
                  <div className="flex items-baseline gap-1 mt-0.5">
                    <span className={`text-xl font-bold font-mono ${selectedPatient.vitals.systolicBP < 90 || selectedPatient.vitals.systolicBP >= 180 ? 'text-rose-600' : 'text-slate-900'}`}>
                      {selectedPatient.vitals.systolicBP}/{selectedPatient.vitals.diastolicBP}
                    </span>
                    <span className="text-[10px] text-slate-400 font-medium">mmHg</span>
                  </div>
                </div>

                <div className="p-3 rounded-2xl bg-slate-50 border border-slate-200/70">
                  <div className="text-[10px] text-slate-400 font-semibold uppercase tracking-wider">Breathing Rate</div>
                  <div className="flex items-baseline gap-1 mt-0.5">
                    <span className={`text-xl font-bold font-mono ${selectedPatient.vitals.respiratoryRate >= 22 ? 'text-rose-600' : 'text-slate-900'}`}>
                      {selectedPatient.vitals.respiratoryRate}
                    </span>
                    <span className="text-[10px] text-slate-400 font-medium">/min</span>
                  </div>
                </div>

                <div className="p-3 rounded-2xl bg-slate-50 border border-slate-200/70">
                  <div className="text-[10px] text-slate-400 font-semibold uppercase tracking-wider">Oxygen (SpO2)</div>
                  <div className="flex items-baseline gap-1 mt-0.5">
                    <span className={`text-xl font-bold font-mono ${selectedPatient.vitals.oxygenSaturation < 92 ? 'text-rose-600' : 'text-slate-900'}`}>
                      {selectedPatient.vitals.oxygenSaturation}%
                    </span>
                  </div>
                </div>

                <div className="p-3 rounded-2xl bg-slate-50 border border-slate-200/70">
                  <div className="text-[10px] text-slate-400 font-semibold uppercase tracking-wider">Body Temp</div>
                  <div className="flex items-baseline gap-1 mt-0.5">
                    <span className={`text-xl font-bold font-mono ${selectedPatient.vitals.temperature > 38.0 || selectedPatient.vitals.temperature < 36.0 ? 'text-amber-600' : 'text-slate-900'}`}>
                      {selectedPatient.vitals.temperature}°C
                    </span>
                  </div>
                </div>

                <div className="p-3 rounded-2xl bg-slate-50 border border-slate-200/70">
                  <div className="text-[10px] text-slate-400 font-semibold uppercase tracking-wider">Conscious / Pain</div>
                  <div className="flex items-baseline gap-1 mt-0.5">
                    <span className={`text-xl font-bold font-mono ${selectedPatient.vitals.gcsScore < 15 ? 'text-rose-600' : 'text-slate-900'}`}>
                      {selectedPatient.vitals.gcsScore}/15
                    </span>
                    <span className="text-[10px] text-slate-400 font-medium">(Pain: {selectedPatient.vitals.painScore}/10)</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Lab Biomarkers */}
            <div>
              <label className="text-[11px] uppercase tracking-wider text-slate-400 font-semibold block mb-2">
                Blood & Lab Test Results
              </label>
              <div className="p-3.5 rounded-2xl bg-slate-50 border border-slate-200/70 space-y-2 text-xs">
                {selectedPatient.labs.troponinI !== undefined && (
                  <div className="flex justify-between items-center">
                    <span className="text-slate-500 font-medium">Troponin (Heart Damage):</span>
                    <span className={`font-mono font-bold ${selectedPatient.labs.troponinI > 0.04 ? 'text-rose-600' : 'text-slate-800'}`}>
                      {selectedPatient.labs.troponinI} ng/mL {selectedPatient.labs.troponinI > 0.04 ? '(High - Urgent)' : '(Normal)'}
                    </span>
                  </div>
                )}
                {selectedPatient.labs.lactate !== undefined && (
                  <div className="flex justify-between items-center">
                    <span className="text-slate-500 font-medium">Lactate (Body Stress):</span>
                    <span className={`font-mono font-bold ${selectedPatient.labs.lactate >= 2.0 ? 'text-rose-600' : 'text-slate-800'}`}>
                      {selectedPatient.labs.lactate} mmol/L {selectedPatient.labs.lactate >= 2.0 ? '(Elevated)' : '(Normal)'}
                    </span>
                  </div>
                )}
                {selectedPatient.labs.whiteBloodCellCount !== undefined && (
                  <div className="flex justify-between items-center">
                    <span className="text-slate-500 font-medium">White Blood Cells (Infection):</span>
                    <span className={`font-mono font-bold ${selectedPatient.labs.whiteBloodCellCount > 11.0 ? 'text-amber-600' : 'text-slate-800'}`}>
                      {selectedPatient.labs.whiteBloodCellCount} k/uL {selectedPatient.labs.whiteBloodCellCount > 11.0 ? '(High)' : '(Normal)'}
                    </span>
                  </div>
                )}
                {selectedPatient.labs.bloodGlucose !== undefined && (
                  <div className="flex justify-between items-center">
                    <span className="text-slate-500 font-medium">Blood Sugar (Glucose):</span>
                    <span className={`font-mono font-bold ${selectedPatient.labs.bloodGlucose > 200 ? 'text-amber-600' : 'text-slate-800'}`}>
                      {selectedPatient.labs.bloodGlucose} mg/dL {selectedPatient.labs.bloodGlucose > 200 ? '(High)' : '(Normal)'}
                    </span>
                  </div>
                )}
                {selectedPatient.labs.serumCreatinine !== undefined && (
                  <div className="flex justify-between items-center">
                    <span className="text-slate-500 font-medium">Creatinine (Kidney Health):</span>
                    <span className={`font-mono font-bold ${selectedPatient.labs.serumCreatinine > 1.3 ? 'text-amber-600' : 'text-slate-800'}`}>
                      {selectedPatient.labs.serumCreatinine} mg/dL {selectedPatient.labs.serumCreatinine > 1.3 ? '(High)' : '(Normal)'}
                    </span>
                  </div>
                )}
              </div>
            </div>

            {/* Meds & History */}
            <div className="space-y-3 text-xs">
              <div>
                <span className="text-slate-400 uppercase tracking-wider text-[10px] font-semibold block mb-1.5">Past Health History</span>
                <div className="flex flex-wrap gap-1.5">
                  {selectedPatient.pastMedicalHistory.map((h, i) => (
                    <span key={i} className="px-2.5 py-1 rounded-lg bg-slate-100 text-slate-700 font-medium text-[11px]">
                      {h}
                    </span>
                  ))}
                </div>
              </div>

              <div>
                <span className="text-slate-400 uppercase tracking-wider text-[10px] font-semibold block mb-1.5">Current Regular Medicines</span>
                <div className="flex flex-wrap gap-1.5">
                  {selectedPatient.currentMedications.map((m, i) => (
                    <span key={i} className="px-2.5 py-1 rounded-lg bg-slate-100 text-slate-700 font-medium text-[11px]">
                      {m}
                    </span>
                  ))}
                </div>
              </div>

              <div>
                <span className="text-slate-400 uppercase tracking-wider text-[10px] font-semibold block mb-1.5">Proposed Hospital Medicines</span>
                <div className="flex flex-wrap gap-1.5">
                  {selectedPatient.proposedMedications.map((m, i) => (
                    <span key={i} className="px-2.5 py-1 rounded-lg bg-sky-50 text-sky-700 border border-sky-200 font-semibold text-[11px]">
                      {m}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Right Column: Autonomous Agent Execution & Diagnostic Results */}
        <div className="lg:col-span-8 space-y-6">
          {/* Agent Workflow Stepper */}
          <div className="bg-white border border-slate-200/80 rounded-2xl sm:rounded-3xl p-5 shadow-sm">
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center gap-2">
                <Zap className="w-4 h-4 text-sky-600" />
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-900">
                  AI Decision Pipeline (5 Automatic Steps)
                </h3>
              </div>
              <span className="text-[11px] font-mono font-medium text-slate-500">
                {isRunningAgent ? 'Analyzing patient...' : `Speed: ${agentResult?.totalProcessingTimeMs || 0}ms`}
              </span>
            </div>

            {/* Step badges */}
            <div className="grid grid-cols-1 sm:grid-cols-5 gap-2">
              {stepLabels.map((label, idx) => {
                const isCompleted = !isRunningAgent || activeStepIndex >= idx;
                const isCurrent = isRunningAgent && activeStepIndex === idx;
                return (
                  <div
                    key={idx}
                    className={`p-2.5 rounded-xl border text-xs transition-all ${
                      isCurrent
                        ? 'bg-sky-500 border-sky-600 text-white font-semibold shadow-sm shadow-sky-500/25 animate-pulse'
                        : isCompleted
                        ? 'bg-sky-50/70 border-sky-200 text-sky-900 font-medium'
                        : 'bg-slate-50 border-slate-200 text-slate-400'
                    }`}
                  >
                    <div className="flex items-center gap-1.5 font-medium">
                      {isCompleted ? (
                        <CheckCircle2 className={`w-3.5 h-3.5 shrink-0 ${isCurrent ? 'text-white' : 'text-sky-600'}`} />
                      ) : (
                        <div className="w-3.5 h-3.5 rounded-full border border-slate-300 shrink-0" />
                      )}
                      <span className="truncate">{label}</span>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Primary Triage Category Banner */}
          {agentResult && (
            <div className={`p-6 rounded-2xl sm:rounded-3xl border ${currentTriage.bg} shadow-sm space-y-4`}>
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                <div className="flex items-center gap-3">
                  <div className={`w-3.5 h-3.5 rounded-full ${currentTriage.dot} animate-ping`} />
                  <div>
                    <span className="text-[10px] font-bold uppercase tracking-widest text-slate-500">
                      Emergency Risk Level
                    </span>
                    <h3 className="text-xl font-extrabold tracking-tight text-slate-900">
                      {currentTriage.label}
                    </h3>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-xs px-3 py-1 rounded-full font-mono font-bold bg-white border border-slate-200 text-slate-800 shadow-xs" title="National Early Warning Score (Vitals Risk)">
                    Vitals Score (NEWS2): {agentResult.mlAssessment.news2Score}/20
                  </span>
                  <span className="text-xs px-3 py-1 rounded-full font-mono font-bold bg-white border border-slate-200 text-slate-800 shadow-xs" title="Quick Sepsis Organ Failure Assessment">
                    Infection Risk (qSOFA): {agentResult.mlAssessment.qSofaScore}/3
                  </span>
                </div>
              </div>

              {/* Numerical Risk & Readmission probability bars */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-3 border-t border-slate-200/80">
                <div>
                  <div className="flex justify-between text-xs font-semibold mb-1">
                    <span className="text-slate-600">AI Critical Emergency Probability:</span>
                    <span className="font-mono text-sky-700 font-bold">
                      {(agentResult.mlAssessment.criticalityScore * 100).toFixed(1)}%
                    </span>
                  </div>
                  <div className="w-full h-2.5 rounded-full bg-slate-200/80 overflow-hidden">
                    <div
                      className={`h-full transition-all duration-700 ${
                        agentResult.mlAssessment.criticalityScore > 0.6 ? 'bg-rose-500' : 'bg-sky-500'
                      }`}
                      style={{ width: `${agentResult.mlAssessment.criticalityScore * 100}%` }}
                    />
                  </div>
                </div>

                <div>
                  <div className="flex justify-between text-xs font-semibold mb-1">
                    <span className="text-slate-600">30-Day Hospital Readmission Risk:</span>
                    <span className="font-mono text-amber-700 font-bold">
                      {(agentResult.mlAssessment.readmissionRisk30Day * 100).toFixed(1)}%
                    </span>
                  </div>
                  <div className="w-full h-2.5 rounded-full bg-slate-200/80 overflow-hidden">
                    <div
                      className="h-full bg-amber-500 transition-all duration-700"
                      style={{ width: `${agentResult.mlAssessment.readmissionRisk30Day * 100}%` }}
                    />
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Pharmacology Drug Safety Alerts */}
          {agentResult && agentResult.drugSafetyAlerts.length > 0 && (
            <div className="bg-rose-50 border border-rose-200 rounded-2xl sm:rounded-3xl p-5 shadow-sm space-y-3">
              <div className="flex items-center gap-2 text-rose-700">
                <AlertTriangle className="w-5 h-5 shrink-0" />
                <h4 className="font-bold text-sm uppercase tracking-wider">
                  Medicine Warning: {agentResult.drugSafetyAlerts.length} Unsafe Medicine Combinations Found
                </h4>
              </div>

              <div className="space-y-3">
                {agentResult.drugSafetyAlerts.map((alert, idx) => (
                  <div key={idx} className="p-4 rounded-2xl bg-white border border-rose-200/80 space-y-1.5 text-xs shadow-xs">
                    <div className="flex items-center justify-between">
                      <span className="font-bold text-rose-900 text-sm">
                        {alert.drugA} + {alert.drugB}
                      </span>
                      <span className="px-2.5 py-0.5 rounded-full text-[10px] font-mono font-bold uppercase bg-rose-100 text-rose-700 border border-rose-200">
                        {alert.severity === 'CONTRAINDICATED' ? 'DO NOT GIVE TOGETHER' : alert.severity}
                      </span>
                    </div>
                    <p className="text-slate-600 leading-relaxed">{alert.mechanism}</p>
                    <div className="pt-1.5 text-sky-700 font-medium">
                      <span className="text-slate-500">Doctor's Action: </span>
                      {alert.clinicalRecommendation}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Differential Diagnosis & Clinical Synthesis */}
          {agentResult && (
            <div className="bg-[#1E293B] rounded-3xl p-6 text-white shadow-md space-y-5">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  <span className="w-2.5 h-2.5 bg-sky-400 rounded-full animate-pulse"></span>
                  <h4 className="font-bold text-base tracking-tight text-white">
                    Doctor's Diagnosis & AI Treatment Recommendations
                  </h4>
                </div>
                <span className="text-[11px] px-3 py-1 rounded-full bg-white/10 text-sky-300 font-mono border border-white/10">
                  AI Model: Active
                </span>
              </div>

              {/* Executive Summary */}
              <div className="p-4 rounded-2xl bg-white/5 border border-white/10 text-xs text-slate-200 leading-relaxed">
                {agentResult.clinicalSynthesis.executiveSummary}
              </div>

              {/* Differential Diagnosis Table */}
              <div className="space-y-2.5">
                {agentResult.clinicalSynthesis.differentialDiagnosis.map((item, idx) => (
                  <div key={idx} className="p-4 rounded-2xl bg-white/5 border border-white/10 space-y-1.5 text-xs">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <span className="font-bold text-white text-sm">{item.condition}</span>
                        <span className="px-2 py-0.5 rounded bg-sky-950 text-sky-300 font-mono text-[10px] border border-sky-800/60">
                          Code: {item.icd10Code}
                        </span>
                      </div>
                      <span className={`text-[10px] font-bold px-2.5 py-0.5 rounded-full ${
                        item.probability === 'HIGH' ? 'bg-rose-500/30 text-rose-300 border border-rose-500/40' : 'bg-amber-500/30 text-amber-300 border border-amber-500/40'
                      }`}>
                        {item.probability} CHANCE
                      </span>
                    </div>
                    <p className="text-slate-300 text-[11px] leading-relaxed">{item.justification}</p>
                  </div>
                ))}
              </div>

              {/* Immediate Clinical Orders & Action Items */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
                <div className="p-4 rounded-2xl bg-white/5 border border-white/10 space-y-2">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-sky-400 block">
                    Immediate Action Steps
                  </span>
                  <ul className="space-y-1.5 text-xs text-slate-300">
                    {agentResult.clinicalSynthesis.immediateActions.map((action, i) => (
                      <li key={i} className="flex items-start gap-2">
                        <ArrowRight className="w-3.5 h-3.5 text-sky-400 mt-0.5 shrink-0" />
                        <span>{action}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="p-4 rounded-2xl bg-white/5 border border-white/10 space-y-2">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-sky-400 block">
                    Recommended Tests & Hospital Ward
                  </span>
                  <ul className="space-y-1.5 text-xs text-slate-300">
                    {agentResult.clinicalSynthesis.recommendedLabsAndImaging.map((item, i) => (
                      <li key={i} className="flex items-start gap-2">
                        <Check className="w-3.5 h-3.5 text-emerald-400 mt-0.5 shrink-0" />
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                  <div className="pt-2 mt-2 border-t border-white/10 flex items-center justify-between text-xs">
                    <span className="text-slate-400">Recommended Ward:</span>
                    <span className="font-bold text-white font-mono px-2.5 py-0.5 rounded-lg bg-white/10 border border-white/10">
                      {agentResult.clinicalSynthesis.dispositionRecommendation === 'ICU_ADMISSION' ? 'Intensive Care Unit (ICU)' :
                       agentResult.clinicalSynthesis.dispositionRecommendation === 'STEP_DOWN_UNIT' ? 'High Dependency / Step-Down' :
                       agentResult.clinicalSynthesis.dispositionRecommendation === 'GENERAL_WARD' ? 'General Medical Ward' :
                       agentResult.clinicalSynthesis.dispositionRecommendation === 'OBSERVATION_UNIT' ? 'Emergency Observation Ward' :
                       'Discharge with Home Care & Followup'}
                    </span>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Grounded Clinical Protocol RAG Citations */}
          {agentResult && agentResult.retrievedGuidelines.length > 0 && (
            <div className="bg-white border border-slate-200/80 rounded-2xl sm:rounded-3xl p-6 shadow-sm space-y-4">
              <div className="flex items-center gap-2">
                <FileText className="w-5 h-5 text-sky-600" />
                <h4 className="font-bold text-sm uppercase tracking-wider text-slate-900">
                  Official Medical Guidelines Applied (WHO, AHA, NICE)
                </h4>
              </div>

              <div className="space-y-3">
                {agentResult.retrievedGuidelines.map((chunk, i) => (
                  <div key={i} className="p-4 rounded-2xl bg-slate-50 border border-slate-200/70 space-y-1.5 text-xs">
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1">
                      <span className="font-bold text-sky-700 text-xs">{chunk.guidelineTitle}</span>
                      <span className="text-[10px] font-mono text-slate-500 font-semibold">
                        Match: {(Number(chunk.relevanceScore || 0.85) * 100).toFixed(0)}% • Grade: {chunk.evidenceGrade}
                      </span>
                    </div>
                    <div className="text-[11px] font-semibold text-slate-700">
                      {chunk.sectionTitle} ({chunk.authoringBody}, {chunk.publishedYear})
                    </div>
                    <p className="text-slate-600 text-[11px] leading-relaxed italic border-l-2 border-sky-400 pl-3">
                      "{chunk.content}"
                    </p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Automated SOAP Clinical Documentation Card */}
          {agentResult && agentResult.clinicalSynthesis.soapNote && (
            <div className="bg-white border border-slate-200/80 rounded-2xl sm:rounded-3xl p-6 shadow-sm space-y-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <FileText className="w-5 h-5 text-sky-600" />
                  <h4 className="font-bold text-sm uppercase tracking-wider text-slate-900">
                    Doctor's Clinical SOAP Note (Ready for Hospital Records)
                  </h4>
                </div>
                <button
                  id="copy-soap-note-btn"
                  onClick={handleCopySOAP}
                  className="flex items-center gap-1.5 text-xs font-bold px-3.5 py-1.5 rounded-xl bg-sky-500 hover:bg-sky-600 text-white transition-all shadow-sm shadow-sky-500/20 cursor-pointer"
                >
                  {copiedSOAP ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copiedSOAP ? 'Copied to Clipboard!' : 'Copy Doctor Note'}</span>
                </button>
              </div>

              <div className="p-5 rounded-2xl bg-slate-50 font-mono text-xs text-slate-800 space-y-3.5 border border-slate-200/80">
                <div>
                  <span className="text-sky-700 font-bold block">[SUBJECTIVE - Patient Story & Symptoms]</span>
                  <p className="mt-0.5 leading-relaxed text-slate-700 font-sans text-xs">{agentResult.clinicalSynthesis.soapNote.subjective}</p>
                </div>
                <div>
                  <span className="text-sky-700 font-bold block">[OBJECTIVE - Vitals & Test Findings]</span>
                  <p className="mt-0.5 leading-relaxed text-slate-700 font-sans text-xs">{agentResult.clinicalSynthesis.soapNote.objective}</p>
                </div>
                <div>
                  <span className="text-sky-700 font-bold block">[ASSESSMENT - Diagnosis & Danger Level]</span>
                  <p className="mt-0.5 leading-relaxed text-slate-700 font-sans text-xs">{agentResult.clinicalSynthesis.soapNote.assessment}</p>
                </div>
                <div>
                  <span className="text-sky-700 font-bold block">[PLAN - Treatment, Medicines & Hospital Ward]</span>
                  <p className="mt-0.5 leading-relaxed text-slate-700 font-sans text-xs">{agentResult.clinicalSynthesis.soapNote.plan}</p>
                </div>
              </div>
            </div>
          )}

          {/* Interactive Agent Step Execution Trace (Audit Trail) */}
          {agentResult && agentResult.agentTrace && (
            <div className="bg-white border border-slate-200/80 rounded-2xl sm:rounded-3xl p-6 shadow-sm space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Layers className="w-5 h-5 text-sky-600" />
                  <h4 className="font-bold text-sm uppercase tracking-wider text-slate-900">
                    Step-by-Step AI Reasoning Log
                  </h4>
                </div>
                <span className="text-xs text-slate-500 font-medium">5 Automatic Tools Called</span>
              </div>

              <div className="space-y-2">
                {agentResult.agentTrace.map((trace, idx) => {
                  const isExpanded = expandedTraceIndex === idx;
                  return (
                    <div key={idx} className="rounded-2xl border border-slate-200/80 bg-slate-50 overflow-hidden text-xs">
                      <button
                        onClick={() => setExpandedTraceIndex(isExpanded ? null : idx)}
                        className="w-full px-4 py-3.5 flex items-center justify-between hover:bg-slate-100/80 text-left transition-colors"
                      >
                        <div className="flex items-center gap-2.5">
                          <span className="w-5 h-5 rounded-full bg-sky-100 text-sky-700 font-mono text-[11px] flex items-center justify-center font-bold border border-sky-200">
                            {trace.stepNumber}
                          </span>
                          <span className="font-bold text-slate-800">{trace.toolName}</span>
                          <span className="text-[10px] font-mono text-slate-500 hidden sm:inline font-semibold">
                            ({trace.executionDurationMs}ms)
                          </span>
                        </div>
                        <div className="flex items-center gap-2">
                          <span className="px-2.5 py-0.5 rounded-full text-[10px] font-mono font-bold bg-sky-100 text-sky-700 border border-sky-200">
                            COMPLETED
                          </span>
                          {isExpanded ? <ChevronUp className="w-4 h-4 text-slate-500" /> : <ChevronDown className="w-4 h-4 text-slate-500" />}
                        </div>
                      </button>

                      {isExpanded && (
                        <div className="px-4 pb-4 pt-1 space-y-2.5 border-t border-slate-200 text-slate-700">
                          <p className="text-slate-600 text-xs">{trace.description}</p>
                          <div className="p-3 rounded-xl bg-sky-50/70 border border-sky-200 font-mono text-[11px] text-sky-900">
                            <span className="text-sky-700 font-bold block mb-1">Agent Reasoning:</span>
                            {trace.reasoningSnippet}
                          </div>
                          <div className="grid grid-cols-1 md:grid-cols-2 gap-2 text-[11px] font-mono">
                            <div className="p-3 rounded-xl bg-slate-900 text-slate-200 border border-slate-800 overflow-x-auto">
                              <span className="text-sky-400 font-bold block mb-1">Tool Input:</span>
                              <pre>{JSON.stringify(trace.inputPayload, null, 2)}</pre>
                            </div>
                            <div className="p-3 rounded-xl bg-slate-900 text-slate-200 border border-slate-800 overflow-x-auto">
                              <span className="text-sky-400 font-bold block mb-1">Tool Output:</span>
                              <pre>{JSON.stringify(trace.outputPayload, null, 2)}</pre>
                            </div>
                          </div>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Custom Patient Intake Modal */}
      {showCustomModal && (
        <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4 overflow-y-auto">
          <div className="bg-white border border-slate-200 rounded-3xl max-w-2xl w-full p-6 space-y-4 shadow-2xl">
            <div className="flex items-center justify-between border-b border-slate-100 pb-3">
              <h3 className="font-bold text-base text-slate-900 flex items-center gap-2">
                <PlusCircle className="w-5 h-5 text-sky-600" />
                Add New Emergency Patient
              </h3>
              <button
                onClick={() => setShowCustomModal(false)}
                className="text-slate-400 hover:text-slate-700 text-xs font-bold px-2 py-1 cursor-pointer"
              >
                ✕ Close
              </button>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
              <div>
                <label className="text-slate-500 block mb-1 font-semibold">Patient Name</label>
                <input
                  type="text"
                  value={customForm.name}
                  onChange={e => setCustomForm({ ...customForm, name: e.target.value })}
                  placeholder="e.g. Pooja Sharma"
                  className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-slate-900 font-medium focus:outline-none focus:border-sky-500"
                />
              </div>
              <div>
                <label className="text-slate-500 block mb-1 font-semibold">Age (Years)</label>
                <input
                  type="number"
                  value={customForm.age}
                  onChange={e => setCustomForm({ ...customForm, age: Number(e.target.value) })}
                  className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-slate-900 font-medium focus:outline-none focus:border-sky-500"
                />
              </div>
              <div>
                <label className="text-slate-500 block mb-1 font-semibold">Gender</label>
                <select
                  value={customForm.gender}
                  onChange={e => setCustomForm({ ...customForm, gender: e.target.value as 'MALE' | 'FEMALE' })}
                  className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-slate-900 font-medium focus:outline-none focus:border-sky-500"
                >
                  <option value="FEMALE">Female</option>
                  <option value="MALE">Male</option>
                  <option value="OTHER">Other</option>
                </select>
              </div>
            </div>

            <div className="text-xs">
              <label className="text-slate-500 block mb-1 font-semibold">Main Symptoms & Health Complaint</label>
              <textarea
                rows={2}
                value={customForm.chiefComplaint}
                onChange={e => setCustomForm({ ...customForm, chiefComplaint: e.target.value })}
                placeholder="Describe symptoms in simple words..."
                className="w-full px-3 py-2 bg-slate-50 border border-slate-200 rounded-xl text-slate-900 font-medium focus:outline-none focus:border-sky-500"
              />
            </div>

            {/* Vitals inputs */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs">
              <div>
                <label className="text-slate-500 block mb-1 font-semibold">Heart Rate (BPM)</label>
                <input
                  type="number"
                  value={customForm.vitals?.heartRate}
                  onChange={e => setCustomForm({
                    ...customForm,
                    vitals: { ...customForm.vitals!, heartRate: Number(e.target.value) }
                  })}
                  className="w-full px-2.5 py-1.5 bg-slate-50 border border-slate-200 rounded-xl text-slate-900 font-mono"
                />
              </div>
              <div>
                <label className="text-slate-500 block mb-1 font-semibold">Blood Pressure (mmHg)</label>
                <input
                  type="number"
                  value={customForm.vitals?.systolicBP}
                  onChange={e => setCustomForm({
                    ...customForm,
                    vitals: { ...customForm.vitals!, systolicBP: Number(e.target.value) }
                  })}
                  className="w-full px-2.5 py-1.5 bg-slate-50 border border-slate-200 rounded-xl text-slate-900 font-mono"
                />
              </div>
              <div>
                <label className="text-slate-500 block mb-1 font-semibold">Breathing (/min)</label>
                <input
                  type="number"
                  value={customForm.vitals?.respiratoryRate}
                  onChange={e => setCustomForm({
                    ...customForm,
                    vitals: { ...customForm.vitals!, respiratoryRate: Number(e.target.value) }
                  })}
                  className="w-full px-2.5 py-1.5 bg-slate-50 border border-slate-200 rounded-xl text-slate-900 font-mono"
                />
              </div>
              <div>
                <label className="text-slate-500 block mb-1 font-semibold">Oxygen SpO2 (%)</label>
                <input
                  type="number"
                  value={customForm.vitals?.oxygenSaturation}
                  onChange={e => setCustomForm({
                    ...customForm,
                    vitals: { ...customForm.vitals!, oxygenSaturation: Number(e.target.value) }
                  })}
                  className="w-full px-2.5 py-1.5 bg-slate-50 border border-slate-200 rounded-xl text-slate-900 font-mono"
                />
              </div>
            </div>

            <div className="flex justify-end gap-2 pt-3 border-t border-slate-100">
              <button
                onClick={() => setShowCustomModal(false)}
                className="px-4 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-semibold cursor-pointer"
              >
                Cancel
              </button>
              <button
                id="submit-custom-patient-btn"
                onClick={() => {
                  const newP: PatientRecord = {
                    ...(customForm as PatientRecord),
                    id: `PT-IN-${Date.now().toString().slice(-4)}`,
                    timestamp: new Date().toISOString()
                  };
                  setSelectedPatient(newP);
                  setShowCustomModal(false);
                }}
                className="px-5 py-2 rounded-xl bg-sky-500 hover:bg-sky-600 text-white text-xs font-bold shadow-sm shadow-sky-500/20 cursor-pointer"
              >
                Analyze Patient
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
